In [4]:
import numpy as np

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = "TUPM-25-0389"

# Extract numeric part
seed_value = int(STUDENT_ID.split('-')[2])

np.random.seed(seed_value)

data = np.random.randint(1, seed_value % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)

Adam Niegel S. Aspiras's Array: [103  85 130 106  90  48  54 111 108  52]


In [8]:
import numpy as np 

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = "TUPM-25-0389"

# Convert ID to a usable integer seed
seed_value = int(STUDENT_ID.split('-')[2])
np.random.seed(seed_value)

# Create matrix
matrix = np.random.randint(1, seed_value % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

# Row and column sums
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)

print("Row sums:", row_sums)
print("Column sums:", col_sums)

Adam Niegel S. Aspiras's Matrix:
 [[39 21  2 42]
 [26 48 13 54]
 [47  1 44 46]]
Row sums: [104 141 138]
Column sums: [112  70  59 142]


In [10]:
import numpy as np

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = 250389  # use numbers only (from your ID)

np.random.seed(STUDENT_ID)

arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3, 3, 3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:, 1, :]
print("Slice[:,1,:]:\n", slice_mid)

Adam Niegel S. Aspiras's 3D Array:
 [[[ 0  0 12]
  [ 0 10 12]
  [18  3  4]]

 [[ 5 17  9]
  [ 8  6  7]
  [11  7  1]]

 [[ 5  5 11]
  [13  4  5]
  [ 6  3 14]]]
Slice[:,1,:]:
 [[ 0 10 12]
 [ 8  6  7]
 [13  4  5]]


In [11]:
import numpy as np

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

np.random.seed(STUDENT_ID)

x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)

filtered = x[(x > STUDENT_ID % 50) & (x < STUDENT_ID % 100)]

print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Adam Niegel S. Aspiras's Original: [103  85 130 106  90  48  54 111 108  52]
Filtered subset: [85 48 54 52]


In [12]:
import numpy as np

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

np.random.seed(STUDENT_ID)

A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2, 2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2, 2))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)

print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[39 21]
 [ 2 42]]
Matrix B:
 [[26 48]
 [13 54]]
A @ B:
 [[1287 3006]
 [ 598 2364]]
Determinant of A: 1595.9999999999993


In [13]:
import numpy as np

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

# Generate 8 evenly spaced angles from 0 to 2π
angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)

print(f"{STUDENT_NAME}'s ({STUDENT_ID}) Angles:\n", angles)
print("\nSine:\n", sine_vals)
print("\nCosine:\n", cos_vals)

Adam Niegel S. Aspiras's (389) Angles:
 [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]

Sine:
 [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]

Cosine:
 [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [14]:
import numpy as np

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2]) # Result: 389

# Set the seed for reproducibility
np.random.seed(STUDENT_ID)

# Generate a 4x4 array of random integers
# The upper bound is 389 % 50 + 20 = 59
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))

# Apply the step-slicing to set specific elements to 0
arr[::2, ::2] = 0

print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Adam Niegel S. Aspiras's Modified 4x4 Array:
 [[ 0 21  0 42]
 [26 48 13 54]
 [ 0  1  0 46]
 [52 42 38 46]]


In [15]:
import numpy as np

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2]) # Result: 389

# Set seed for consistent random results
np.random.seed(STUDENT_ID)

# Generate 10 random scores
# Range: 0 to (389 % 100 + 50) = 139
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)

# Vectorized conditional logic
# Threshold: 389 % 70 = 39
grades = np.where(scores >= STUDENT_ID % 70, 'Pass', 'Fail')

print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Adam Niegel S. Aspiras's Scores: [102  84 129 105  89  47  53 110 107  51]
Grades: ['Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']


In [16]:
import numpy as np

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2]) # Result: 389

np.random.seed(STUDENT_ID)

# Generate a 3x4 array of random integers
# Upper bound: 389 % 50 + 20 = 59
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))

# Flatten the array to a 1D version
flat_arr = arr.flatten()

# Transpose the array (swap rows and columns)
transposed_arr = arr.T

print(f"{STUDENT_NAME}'s Original array:\n", arr)
print("\nFlattened:", flat_arr)
print("\nTransposed:\n", transposed_arr)

Adam Niegel S. Aspiras's Original array:
 [[39 21  2 42]
 [26 48 13 54]
 [47  1 44 46]]

Flattened: [39 21  2 42 26 48 13 54 47  1 44 46]

Transposed:
 [[39 26 47]
 [21 48  1]
 [ 2 13 44]
 [42 54 46]]


In [17]:
import numpy as np

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1

print(f"{STUDENT_NAME}'s Array with conditional replacements:\n", arr)

Adam Niegel S. Aspiras's Array with conditional replacements:
 [[39 21 -1]
 [-1 -1 -1]
 [13 -1 47]]


In [19]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Name': [STUDENT_NAME] * 5,
    'Score': np.random.randint(STUDENT_ID % 50, STUDENT_ID % 100 + 50, 5),
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})

print(df)

                     Name  Score  YearsCodePro
0  Adam Niegel S. Aspiras    123            12
1  Adam Niegel S. Aspiras     40            14
2  Adam Niegel S. Aspiras    101             0
3  Adam Niegel S. Aspiras    128            11
4  Adam Niegel S. Aspiras     86            13


In [22]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()

print(f"Student: {STUDENT_NAME} (ID: {STUDENT_ID})")
print(avg_salary)

Student: Adam Niegel S. Aspiras (ID: 389)
EdLevel
Bachelor    102951.5
Master       78793.0
PhD         146625.0
Name: ConvertedComp, dtype: float64


In [23]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

top5 = df.sort_values(by='ConvertedComp', ascending=False)

print(f"Student: {STUDENT_NAME}")
print(top5)

Student: Adam Niegel S. Aspiras
       Country  ConvertedComp
2           UK         146625
0  Philippines         103078
3       Canada         102825
1          USA          88980
4      Germany          68606


In [24]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Name': [STUDENT_NAME] * 5,
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})

# Filter: YearsCodePro > (389 % 10 = 9)
high_exp = df[df['YearsCodePro'] > STUDENT_ID % 10]

print(high_exp)

                     Name  YearsCodePro
3  Adam Niegel S. Aspiras            15
4  Adam Niegel S. Aspiras            12


In [27]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

np.random.seed(STUDENT_ID)

df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']

df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)

print(f"Student: {STUDENT_NAME} ({STUDENT_ID})")
print(df)

Student: Adam Niegel S. Aspiras (389)
   ConvertedComp   Bracket
0         103078  100-150k
1          88980   50-100k
2         146625  100-150k
3         102825  100-150k
4          68606   50-100k


In [28]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

np.random.seed(STUDENT_ID)

# Create DataFrame with a functional salary range
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

# Apply natural logarithm to the compensation
df['LogComp'] = np.log(df['ConvertedComp'])

print(f"Student: {STUDENT_NAME}")
print(df)

Student: Adam Niegel S. Aspiras
   ConvertedComp    LogComp
0         103078  11.543241
1          88980  11.396167
2         146625  11.895634
3         102825  11.540784
4          68606  11.136135


In [29]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5),
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

corr_matrix = df.corr()

print(f"Student: {STUDENT_NAME}")
print(corr_matrix)

Student: Adam Niegel S. Aspiras
               YearsCodePro  ConvertedComp
YearsCodePro        1.00000        0.52175
ConvertedComp       0.52175        1.00000


In [30]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean', 'median', 'std']).reset_index()

print(f"Student: {STUDENT_NAME} ({STUDENT_ID})")
print(summary)

Student: Adam Niegel S. Aspiras (389)
    EdLevel      mean    median           std
0  Bachelor  102951.5  102951.5    178.898016
1    Master   78793.0   78793.0  14406.593560
2       PhD  146625.0  146625.0           NaN


In [31]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

np.random.seed(STUDENT_ID)

# Generate salaries based on the random seed
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

threshold = 110000

# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')

print(f"Student: {STUDENT_NAME}")
print(df)

Student: Adam Niegel S. Aspiras
   ConvertedComp HighPay
0         103078      No
1          88980      No
2         146625     Yes
3         102825      No
4          68606      No


In [32]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Adam Niegel S. Aspiras"
STUDENT_ID = int("TUPM-25-0389".split('-')[2])

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean', 'max'])

print(f"Student: {STUDENT_NAME} ({STUDENT_ID})")
print(top_countries)

Student: Adam Niegel S. Aspiras (389)
                 mean     max
Country                      
Canada       102825.0  102825
Germany       68606.0   68606
Philippines  103078.0  103078
UK           146625.0  146625
USA           88980.0   88980
